moto_gpt_config_path: "/hpc/home/mgovind1/code/Moto/moto_gpt/configs/models/actPredFalse_motionPredTrue_visionMaeLarge_seq2_chunk3_maskProb0.5.yaml"
latent_motion_tokenizer_path: "/work/mgovind1/Moto/checkpoints/latent_motion_tokenizer_trained_on_bridge/saved_epoch_20_step_105620"
dataset_config_path: "/hpc/home/mgovind1/code/Moto/moto_gpt/configs/data/bridge.yaml"
dataloader_config:
  bs_per_gpu: 16
  workers_per_gpu: 7
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 4
  save_epochs: 2
  save_steps: 10000
  save_path: "/work/mgovind1/Moto/checkpoints/moto_gpt_pretrained_on_bridge/data_bridge-model_actPredFalse_motionPredTrue_visionMaeLarge_seq2_chunk3_maskProb0.5-train_lr0.001_bs512-aug_shiftTrue_resizedCropFalse-lmt-20epoch"
  resume_ckpt_path: null
  max_epoch: 10
  pred_binary_gripper_action: false