latent_motion_tokenizer_config_path: "/hpc/home/mgovind1/code/Moto/latent_motion_tokenizer/configs/models/vq_size128_dim32_num8_legacyTrue-vision_MaeLarge-decoder_queryFusionModeAdd_Patch196_useMaskFalse-mformer_legacyTrue.yaml"
dataset_config_path: "/hpc/home/mgovind1/code/Moto/latent_motion_tokenizer/configs/data/calvin.yaml"
dataloader_config:
  bs_per_gpu: 32
  workers_per_gpu: 15
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "/work/mgovind1/Moto/checkpoints/latent_motion_tokenizer_trained_on_calvin-2/"
  resume_ckpt_path: null